# -*- coding: utf-8 -*-
"""periodic_table_property_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/adishvpudale/ed68bca888608ca9c477b11b0befec62/periodic_table_property_analyzer.ipynb
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings('ignore')

st.set_page_config(page_title="Element Property Predictor", layout="wide")
st.title("🔬 Periodic Table Property Linearization & Predictor")

# Upload CSV
uploaded_file = st.file_uploader("Upload your CSV file", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)

    # Clean & rename columns
    df.columns = [c.strip().replace(" ", "").replace("_", "").lower() for c in df.columns]
    rename_map = {
        'atomicnumber':'atomicNumber', 'symbol':'symbol', 'name':'name',
        'atomicmass':'atomicMass', 'boilingpoint':'boilingPoint',
        'meltingpoint':'meltingPoint', 'firstionizationenergy':'firstIonizationEnergy',
        'ionizationenergy':'firstIonizationEnergy', 'density':'density',
        'atomicradius':'atomicRadius', 'electronegativity':'electronegativity',
        'electronaffinity':'electronAffinity'
    }
    df.rename(columns={k:v for k,v in rename_map.items() if k in df.columns}, inplace=True)

    # Add period if missing
    if 'period' not in df.columns:
        def get_period(z):
            if z <= 2: return 1
            elif z <= 10: return 2
            elif z <= 18: return 3
            elif z <= 36: return 4
            elif z <= 54: return 5
            elif z <= 86: return 6
            elif z <= 118: return 7
            else: return np.nan
        df['period'] = df['atomicNumber'].apply(get_period)

    property_units = {
        'boilingPoint': 'K', 'meltingPoint': 'K', 'firstIonizationEnergy': 'eV',
        'density': 'g/cm³', 'atomicRadius': 'pm', 'electronegativity': 'Pauling scale',
        'electronAffinity': 'eV', 'atomicMass': 'g/mol'
    }

    # Find available numeric properties in the uploaded CSV
    numeric_props = [p for p in df.columns if p in property_units]

    if not numeric_props:
        st.error("❌ No recognized numeric properties found in the CSV. Check column names.")
        st.stop()

    # Create number-to-property mapping
    prop_mapping = {i+1: prop for i, prop in enumerate(numeric_props)}
    mapping_df = pd.DataFrame({
        "Number": list(prop_mapping.keys()),
        "Property": list(prop_mapping.values()),
        "Unit": [property_units.get(p, "") for p in prop_mapping.values()]
    })

    st.subheader("📋 Available Properties (Reference Table)")
    st.dataframe(mapping_df, use_container_width=True, hide_index=True)

    # UI Inputs
    col1, col2 = st.columns(2)
    with col1:
        prop_numbers_input = st.text_input("Enter property numbers to analyze (comma separated, e.g., 1,3,5):", "1,2,3")
        range_input = st.text_input("Atomic number range (e.g., 1-50) or 'all':", "all")
    with col2:
        predict_input = st.text_input("Atomic numbers to predict (comma separated, e.g., 119,120):", "119,120")
        compare_input = st.text_input("Two atomic numbers to compare (e.g., 8,16) or 'skip':", "skip")
        period_input = st.text_input("Period number (1-7) to analyze or 'skip':", "skip")

    if st.button("🚀 Run Analysis", type="primary"):
        # Parse property numbers
        try:
            selected_nums = [int(x.strip()) for x in prop_numbers_input.split(",") if x.strip()]
            selected_props = [prop_mapping[n] for n in selected_nums if n in prop_mapping]
            invalid_nums = [n for n in selected_nums if n not in prop_mapping]
            if invalid_nums:
                st.warning(f"⚠️ Ignored invalid property numbers: {invalid_nums}")
            if not selected_props:
                st.error("❌ No valid properties selected. Please enter valid numbers from the table.")
                st.stop()
        except ValueError:
            st.error("❌ Invalid format for property numbers. Use comma-separated integers (e.g., 1,3,5).")
            st.stop()

        # Filter atomic number range
        if range_input.lower() == "all":
            df_range = df.copy()
        else:
            try:
                start, end = map(int, range_input.split("-"))
                df_range = df[(df['atomicNumber'] >= start) & (df['atomicNumber'] <= end)]
                if df_range.empty:
                    st.error(f"❌ No elements found in range {start}-{end}.")
                    st.stop()
            except:
                st.error("❌ Invalid range format. Use 'all' or 'start-end' (e.g., 1-50).")
                st.stop()

        results = {}
        st.subheader("📊 Linear Fits & Plots")

        for prop in selected_props:
            df_prop = df_range[df_range[prop].notna()]
            if df_prop.empty:
                st.warning(f"⚠️ No valid data for {prop}. Skipping.")
                continue

            best_r2 = -np.inf
            best_transform = 'identity'
            best_model = None

            # Try transformations
            for name in ['identity', 'log', 'sqrt', 'reciprocal']:
                try:
                    y_vals = df_prop[prop].values
                    if name == 'log': y_trans = np.log(y_vals)
                    elif name == 'sqrt': y_trans = np.sqrt(y_vals)
                    elif name == 'reciprocal': y_trans = 1 / y_vals
                    else: y_trans = y_vals

                    if np.any(np.isnan(y_trans)) or np.any(np.isinf(y_trans)):
                        continue

                    X = df_prop[['atomicNumber']].values
                    model = LinearRegression()
                    model.fit(X, y_trans)
                    y_pred = model.predict(X)
                    r2 = r2_score(y_trans, y_pred)

                    if r2 > best_r2:
                        best_r2, best_transform, best_model = r2, name, model
                except:
                    continue

            unit = property_units.get(prop, '')
            st.info(f"**{prop}** ({unit}): Best transform = `{best_transform}` (R²={best_r2:.4f})")

            # Prepare plot data
            y_plot = df_prop[prop].values.copy()
            if best_transform == 'log': y_plot = np.log(y_plot)
            elif best_transform == 'sqrt': y_plot = np.sqrt(y_plot)
            elif best_transform == 'reciprocal': y_plot = 1 / y_plot

            y_fit = best_model.predict(df_prop[['atomicNumber']].values)

            fig = px.scatter(x=df_prop['atomicNumber'], y=y_plot,
                             labels={'x':'Atomic Number (Z)', 'y':f'{prop} ({unit})'},
                             title=f'{prop} vs Atomic Number ({best_transform} transform)')
            fig.add_scatter(x=df_prop['atomicNumber'], y=y_fit, mode='lines', name='Linear Fit')
            st.plotly_chart(fig, use_container_width=True)

            results[prop] = {'model': best_model, 'transform': best_transform}

        # Predictions
        if results:
            st.subheader("🔮 Predictions for Unknown Elements")
            try:
                predict_Z_list = [int(z.strip()) for z in predict_input.split(",") if z.strip()]
                if not predict_Z_list:
                    st.warning("⚠️ No atomic numbers entered for prediction.")
                else:
                    pred_data = []
                    for prop, info in results.items():
                        model, transform = info['model'], info['transform']
                        X_pred = np.array(predict_Z_list).reshape(-1,1)
                        y_pred_trans = model.predict(X_pred)

                        if transform == 'identity': y_final = y_pred_trans
                        elif transform == 'log': y_final = np.exp(y_pred_trans)
                        elif transform == 'sqrt': y_final = y_pred_trans**2
                        elif transform == 'reciprocal': y_final = 1 / y_pred_trans

                        unit = property_units.get(prop, '')
                        for i, z in enumerate(predict_Z_list):
                            pred_data.append({'Atomic Number': z, 'Property': prop,
                                              'Predicted Value': round(y_final[i], 4), 'Unit': unit})

                    df_pred = pd.DataFrame(pred_data)
                    st.dataframe(df_pred, use_container_width=True)

                    csv = df_pred.to_csv(index=False).encode('utf-8')
                    st.download_button("📥 Download Predictions CSV", csv, "predicted_elements.csv", "text/csv")
            except Exception as e:
                st.error(f"❌ Prediction error: {e}")

        # Comparison
        if compare_input.lower() != "skip" and selected_props:
            st.subheader("⚖️ Element Comparison")
            try:
                compare_Z = [int(x.strip()) for x in compare_input.split(",") if x.strip()]
                for prop in selected_props:
                    unit = property_units.get(prop, '')
                    st.write(f"**{prop}** ({unit}):")
                    for z in compare_Z:
                        row = df[df['atomicNumber']==z]
                        if not row.empty and pd.notna(row[prop].values[0]):
                            st.write(f"  `Z={z} ({row['symbol'].values[0]})`: {row[prop].values[0]} {unit}")
                        else:
                            st.write(f"  `Z={z}`: data not available")
            except Exception as e:
                st.error(f"❌ Comparison error: {e}")

        # Period Analysis
        if period_input.lower() != "skip":
            st.subheader("📅 Period Analysis")
            try:
                period_number = int(period_input)
                df_period = df[df['period']==period_number]
                if df_period.empty:
                    st.warning(f"⚠️ No data for period {period_number}.")
                else:
                    for prop in selected_props:
                        if prop in df_period.columns:
                            df_p = df_period[df_period[prop].notna()]
                            if df_p.empty: continue
                            fig_p = px.scatter(df_p, x='atomicNumber', y=prop,
                                             title=f'{prop} in Period {period_number}')
                            st.plotly_chart(fig_p, use_container_width=True)
            except ValueError:
                st.error("❌ Invalid period number. Enter an integer 1-7 or 'skip'.")
            except Exception as e:
                st.error(f"❌ Period analysis error: {e}")

else:
    st.info("👆 Please upload a CSV file to begin.")