# -*- coding: utf-8 -*-
"""periodic_table_property_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/adishvpudale/ed68bca888608ca9c477b11b0befec62/periodic_table_property_analyzer.ipynb
"""

from google.colab import files
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

uploaded = files.upload()
csv_file = list(uploaded.keys())[0]
df = pd.read_csv(csv_file)

df.columns = [c.strip().replace(" ","").replace("_","").lower() for c in df.columns]

rename_map = {
    'atomicnumber':'atomicNumber',
    'symbol':'symbol',
    'name':'name',
    'atomicmass':'atomicMass',
    'boilingpoint':'boilingPoint',
    'meltingpoint':'meltingPoint',
    'firstionizationenergy':'firstIonizationEnergy',
    'ionizationenergy':'firstIonizationEnergy',
    'density':'density',
    'atomicradius':'atomicRadius',
    'electronegativity':'electronegativity',
    'electronaffinity':'electronAffinity'
}

df.rename(columns={k:v for k,v in rename_map.items() if k in df.columns}, inplace=True)

if 'period' not in df.columns:
    def get_period(z):
        if z <= 2:
            return 1
        elif z <= 10:
            return 2
        elif z <= 18:
            return 3
        elif z <= 36:
            return 4
        elif z <= 54:
            return 5
        elif z <= 86:
            return 6
        elif z <= 118:
            return 7
        else:
            return np.nan
    df['period'] = df['atomicNumber'].apply(get_period)

property_units = {
    'boilingPoint': 'K',
    'meltingPoint': 'K',
    'firstIonizationEnergy': 'eV',
    'density': 'g/cm³',
    'atomicRadius': 'pm',
    'electronegativity': 'Pauling scale',
    'electronAffinity': 'eV',
    'atomicMass': 'g/mol'
}

def transformations(x):
    return {
        'identity': x,
        'log': np.log(x),
        'sqrt': np.sqrt(x),
        'reciprocal': 1/x
    }

def inverse_transform(y, name):
    if name == 'identity':
        return y
    elif name == 'log':
        return np.exp(y)
    elif name == 'sqrt':
        return y**2
    elif name == 'reciprocal':
        return 1/y

def linear_fit_and_plot(df_prop, prop):
    if prop not in df_prop.columns:
        print("Property '" + prop + "' not found in dataset. Skipping.")
        return None
    df_prop = df_prop[df_prop[prop].notna()]
    if df_prop.empty:
        print("No data available for " + prop + ". Skipping.")
        return None

    best_r2 = -np.inf
    best_transform = 'identity'
    best_model = None
    for name, y_trans in transformations(df_prop[prop].values).items():
        X = df_prop[['atomicNumber']].values
        y = y_trans
        model = LinearRegression()
        model.fit(X, y)
        y_pred = model.predict(X)
        r2 = r2_score(y, y_pred)
        if r2 > best_r2:
            best_r2 = r2
            best_transform = name
            best_model = model

    unit = property_units.get(prop, '')
    print("Best linearization for " + prop + " (" + unit + "): " + best_transform + " (R²=" + str(round(best_r2, 4)) + ")")

    X_plot = df_prop[['atomicNumber']].values
    y_plot = transformations(df_prop[prop].values)[best_transform]
    y_fit = best_model.predict(X_plot)
    fig = px.scatter(x=df_prop['atomicNumber'], y=y_plot, labels={'x':'Atomic Number (Z)','y':prop + " (" + unit + ")"}, title=prop + " vs Atomic Number (" + best_transform + " transform)")
    fig.add_scatter(x=df_prop['atomicNumber'], y=y_fit, mode='lines', name='Linear Fit')
    fig.show()

    return best_model, best_transform

numeric_props = [p for p in df.columns if p in property_units]
print("\nChoose properties to analyze (numeric only):")
print(", ".join(numeric_props))
properties_input = input("Enter properties separated by commas: ")
properties = [p.strip() for p in properties_input.split(",")]

range_input = input("Enter atomic number range (e.g., 1-50) or 'all': ")
if range_input.lower() == "all":
    df_range = df.copy()
else:
    start, end = map(int, range_input.split("-"))
    df_range = df[(df['atomicNumber'] >= start) & (df['atomicNumber'] <= end)]

results = {}
print("\nGenerating linear fits and plots:")
for prop in properties:
    result = linear_fit_and_plot(df_range, prop)
    if result is not None:
        results[prop] = {'model': result[0], 'transform': result[1]}

predict_input = input("\nEnter atomic numbers to predict (comma separated, e.g., 119,120): ")
predict_Z_list = [int(z) for z in predict_input.split(",")]

print("\nPredictions for unknown elements:")
for prop, info in results.items():
    model = info['model']
    transform = info['transform']
    X_pred = np.array(predict_Z_list).reshape(-1,1)
    y_pred_trans = model.predict(X_pred)
    y_pred_final = inverse_transform(y_pred_trans, transform)
    unit = property_units.get(prop, '')
    for i in range(len(predict_Z_list)):
        print(prop + " for Z=" + str(predict_Z_list[i]) + ": " + str(round(y_pred_final[i],4)) + " " + unit)

compare_input = input("\nEnter two atomic numbers to compare (comma separated, e.g., 8,16) or 'skip': ")
if compare_input.lower() != "skip":
    compare_Z = [int(x) for x in compare_input.split(",")]
    for prop in properties:
        unit = property_units.get(prop, '')
        print("\n" + prop + " comparison (" + unit + "):")
        for z in compare_Z:
            row = df[df['atomicNumber']==z]
            if not row.empty and pd.notna(row[prop].values[0]):
                print("Z=" + str(z) + " (" + str(row['symbol'].values[0]) + "): " + str(row[prop].values[0]) + " " + unit)
            else:
                print("Z=" + str(z) + ": data not available")

period_input = input("\nEnter period number (1-7) to analyze or 'skip': ")
if period_input.lower() != "skip":
    period_number = int(period_input)
    df_period = df[df['period']==period_number]
    if df_period.empty:
        print("No data for period " + str(period_number) + ".")
    else:
        for prop in properties:
            if prop in df_period.columns:
                linear_fit_and_plot(df_period, prop)

print("\nAnalysis complete. Scroll up to view plots and predictions with units.")
predictions = []
for prop, info in results.items():
    model = info['model']
    transform = info['transform']
    X_pred = np.array(predict_Z_list).reshape(-1,1)
    y_pred_trans = model.predict(X_pred)
    y_pred_final = inverse_transform(y_pred_trans, transform)
    for i in range(len(predict_Z_list)):
        predictions.append({'atomicNumber': predict_Z_list[i], 'property': prop, 'predicted_value': y_pred_final[i]})

df_pred = pd.DataFrame(predictions)
df_pred.to_csv("predicted_elements.csv", index=False)
print("Predictions saved to predicted_elements.csv")